# Generated by Django 4.2.3 on 2023-07-14 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_topic_closed_alter_topic_pinned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create_date',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='create_date',
            new_name='creation_date',
        ),
    ]
