# Generated by Django 4.2.3 on 2023-07-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='slug',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
