# Generated by Django 4.2.3 on 2023-08-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_remove_userprofile_slug_userprofile_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='d1.png', height_field=128, upload_to='images/user_profile', width_field=128),
        ),
    ]
