# Generated by Django 4.2.3 on 2023-08-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_remove_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='images/user_profile/d1.png', upload_to='images/user_profile'),
        ),
    ]
